### ISSUE TITLE
Detect abort

### ISSUE THREAD

**Issue by andru** [pouchdb/ajax#1]
I'm working on a change for Hoodie to replace `jQuery.ajax` with this library.

I need to be able to check whether a request failed because it was aborted, but as far as I can see there's no way I can currently do this: there's no way to access the XHR instance, and when a request is aborted using the `abort` function provided, the library just gives a generic error:

```
{
error: true,
message: "Database encountered an unknown error",
name: "unknown_error",
status: 500
}
```

I think the easiest path would be if there was a way to get at the xhr instance beneath. Is there any reason you'd be against that? Would you accept a pull request for it and if so any thoughts on the best way to implement it?

**Comment by nolanlawson** [comment]
One thing you should be aware of is that this package has not been integrated into PouchDB proper yet. I created this repo aspirationally, and then the PouchDB issue itself got dropped. So right now this is only used by the pouchdb-load plugin.

**Comment by nolanlawson** [comment]
I think our general strategy is that we would like to shim the `request` library (or a subset of it) for the browser. So yeah, I'd be opposed to exposing the XHR directly; maybe there is some request-y way of detecting aborts?

**Comment by andru** [comment]
Ok thanks @nolanlawson - will this eventually be integrated or is it a dead end? If the former, is it likely to see some big API changes before merge?
Just trying to decide what to use for replacing jQuery.ajax in hoodie.

**Comment by nolanlawson** [comment]
This repo is deprecated. Coming up in the next version of PouchDB, we have an "extras" API where you can pull in the ajax module from PouchDB directly (https://github.com/pouchdb/pouchdb/pull/3730). If you'd like to fix this, please check out the `ajax-browser.js` file over there. :)

**Comment by neojski** [comment]
Haha, I love this repo's commit history :-D
1. initial commit
2. deprecate

**Comment by nolanlawson** [comment]
:)
